### ISSUE TITLE
[1.15.2] Concurrent Modification Exception when placing a boat

### ISSUE THREAD

**Issue by Fogrits** [OnyxStudios/Cardinal-Components-API#26]
I'm using _Winged_ (it embeds Cardinal Components as a library).
Here's the crash report, in short:
---------------------------------------
java.util.ConcurrentModificationException

	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
	at nerdhub.cardinal.components.internal.CardinalEntityInternals.getEntityContainerFactory(CardinalEntityInternals.java:71)
	at net.minecraft.class_1297.handler$zjj001$initDataTracker(class_1297.java:4538)
	at net.minecraft.class_1297.<init>(class_1297.java:256)
	at net.minecraft.class_1690.<init>(class_1690.java:91)
	at net.minecraft.class_1690.<init>(class_1690.java:96)
	at net.minecraft.class_1749.method_7836(class_1749.java:53)
	at net.minecraft.class_1799.method_7913(class_1799.java:206)
	at net.minecraft.class_636.method_2919(class_636.java:348)
	at net.minecraft.class_310.method_1583(class_310.java:1383)
	at net.minecraft.class_310.method_1508(class_310.java:1598)
	at net.minecraft.class_310.method_1574(class_310.java:1445)
	at net.minecraft.class_310.method_1523(class_310.java:964)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Fogrits** [comment]
[Complete Crash Report](https://pastebin.com/ieh3NDHL)

**Comment by Fogrits** [comment]
PS: The boat that I placed down to trigger the crash is "available to use" after I reopen the world to play.

**Comment by Pyrofab** [comment]
Does this always happen when you place a boat, or just sometimes ?

**Comment by Fogrits** [comment]
After the first crash, for some reason, it doesn't crash on the subsequent times I place the boat.

**Comment by Pyrofab** [comment]
So I'm guessing it's caused by a random conflict between the client and the integrated server. I think I know how to fix it.

**Comment by Pyrofab** [comment]
Fix released in [2.3.6](https://github.com/OnyxStudios/Cardinal-Components-API/releases/tag/2.3.6).
If you do not want to wait for Winged to update its bundled version, you can [download the `Cardinal-Components-API` file](https://github.com/OnyxStudios/Cardinal-Components-API/releases/download/2.3.6/Cardinal-Components-API-2.3.6.jar) and put it in your mods folder. It will replace the outdated bundled version.
